"""Generate a compact runtime INI and compiled ABI reference from DIA facts.

Ordinary CI emits disabled profiles. Explicit activation requires the exact
source-matched, reviewed ABI; the executable identity is checked again at runtime.
"""
import argparse
import json
from pathlib import Path
import struct

from discover import PE, canonical_hash


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--candidate", type=Path, required=True)
    parser.add_argument("--exe", type=Path, required=True)
    parser.add_argument("--reference", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--header", type=Path)
    activation = parser.add_mutually_exclusive_group()
    activation.add_argument("--test-checkpoint", action="store_true")
    activation.add_argument("--activate", action="store_true", help="Package the reviewed source-matched adapter")
    args = parser.parse_args()
    c = json.loads(args.candidate.read_text())
    reference = json.loads(args.reference.read_text())
    pe = PE(args.exe.read_bytes())
    from discover import digest
    if digest(pe.data) != c["identity"]["sha256"]:
        raise ValueError("Candidate executable hash mismatch")
    reference_abi = canonical_hash({"symbols": reference["symbols"], "layouts": reference["layouts"]})
    candidate_abi = canonical_hash({"symbols": {k: v["abi_sha256"] for k, v in c["symbols"].items()},
                                    "layouts": {k: v["abi_sha256"] for k, v in c["layouts"].items()}})
    eligible = (c["source_matches_target"] and c["validation"]["identity_verified"] and
                not any(i["required"] for i in c["issues"]) and candidate_abi == reference_abi)
    if (args.test_checkpoint or args.activate or args.header) and not eligible:
        raise ValueError("Only the exact source-matched ABI may emit a test profile/header")
    # Mapped entry validation must account for ASLR's PE DIR64 fixups.
    nt = pe.number(0x3c, "<I")
    reloc_rva, reloc_size = struct.unpack("<II", pe.read(nt + 24 + 112 + 5 * 8, 8))
    fixups = []
    if reloc_size:
        relocs = pe.at_rva(reloc_rva, reloc_size)
        offset = 0
        while offset < len(relocs):
            if len(relocs) - offset < 8:
                raise ValueError("Truncated PE relocation block")
            page, size = struct.unpack_from("<II", relocs, offset)
            if size < 8 or size % 2 or offset + size > len(relocs):
                raise ValueError("Invalid PE relocation block")
            for index in range(offset + 8, offset + size, 2):
                value = struct.unpack_from("<H", relocs, index)[0]
                if value >> 12 == 10:
                    fixups.append(page + (value & 0xfff))
                elif value >> 12 != 0:
                    raise ValueError("Unexpected x64 image fixup type")
            offset += size
    state = "source-matched" if args.activate else ("test-checkpoint" if args.test_checkpoint else "disabled")
    lines = ["; Generated from exact-source DIA discovery; edit source/ABI bindings together.", "[Identity]",
             "Schema=1", "Adapter=upstream-win64-v1", "Activation=" + state,
             "Version=" + c["version"], "SourceCommit=" + c["provenance"]["upstream_commit"],
             "ExecutableSHA256=" + c["identity"]["sha256"], "PdbGUID=" + c["identity"]["pdb_guid"],
             "PdbAge=" + str(c["identity"]["pdb_age"]), "ImageSize=" + str(c["identity"]["image_size"]),
             "AdapterABI=" + candidate_abi, "", "[Symbols]"]
    for role, symbol in c["symbols"].items():
        lines.append(f"{role}={symbol['rva']}")
        lines.append(f"{role}.extent={symbol['extent']}")
        if "entry_bytes" in symbol:
            code = bytes.fromhex(symbol["entry_bytes"])
            mask = bytearray(b"\xff" * len(code))
            for address in fixups:
                for index in range(max(0, address - symbol["rva"]), min(len(code), address + 8 - symbol["rva"])):
                    mask[index] = 0
            lines.append(f"{role}.bytes={code.hex()}")
            lines.append(f"{role}.mask={mask.hex()}")
    if args.header:
        def member(record, name):
            return next(m["offset"] for m in c["layouts"][record]["members"] if m["name"] == name)
        cpu = member("cpuRegistersPack", "cpuRegs")
        offsets = [cpu + member("cpuRegisters", name) for name in ("GPR", "HI", "LO")]
        offsets += [member("cpuRegistersPack", "fpuRegs")]
        offsets += [cpu + member("cpuRegisters", name) for name in ("sa", "pc", "branch", "IsDelaySlot")]
        offsets += [cpu + member("cpuRegisters", "CP0") + 12 * 4]
        header = ['#pragma once', '// Generated by emit-runtime-config.py from the reviewed source-bound ABI facts.',
                  '#include "GuestModuleRuntime.h"', 'namespace StockABI {',
                  'inline constexpr char SourceCommit[] = "' + c['provenance']['upstream_commit'] + '";',
                  'inline constexpr char Fingerprint[] = "' + candidate_abi + '";',
                  'inline constexpr GuestRuntime::Layout Registers{' + ', '.join(map(str, offsets)) + '};',
                  'inline constexpr unsigned AccumulatorOffset = ' + str(member("cpuRegistersPack", "fpuRegs") + member("fpuRegisters", "ACC")) + ';',
                  'inline constexpr PluginHookState::VULayout VU{' + ', '.join(map(str, [c["layouts"]["VURegs"]["size"]] + [member("VURegs", name) for name in ("Mem", "VIBackupCycles", "cycle", "VI", "idx", "fmacreadpos", "fmacwritepos", "fmaccount", "ialureadpos", "ialuwritepos", "ialucount")])) + '};',
                  f'inline constexpr unsigned VURegisterSize = {c["layouts"]["VURegs"]["size"]};',
                  f'inline constexpr unsigned RegisterPackSize = {c["layouts"]["cpuRegistersPack"]["size"]};',
                  f'inline constexpr unsigned ConfigSize = {c["layouts"]["Pcsx2Config"]["size"]};',
                  f'inline constexpr unsigned AspectRatioOffset = {member("Pcsx2Config", "GS") + member("Pcsx2Config::GSOptions", "AspectRatio")};',
                  f'inline constexpr unsigned GSWindowOffset = {member("GSDevice", "m_window_info")};',
                  f'inline constexpr unsigned GSDeviceSize = {c["layouts"]["GSDevice"]["size"]};',
                  f'inline constexpr unsigned WindowHandleOffset = {member("WindowInfo", "window_handle")};',
                  f'inline constexpr unsigned SurfaceWidthOffset = {member("WindowInfo", "surface_width")};',
                  f'inline constexpr unsigned SurfaceHeightOffset = {member("WindowInfo", "surface_height")};',
                  f'inline constexpr unsigned EmuThreadSize = {c["layouts"]["EmuThread"]["size"]};',
                  f'inline constexpr unsigned FullscreenOffset = {member("EmuThread", "m_is_fullscreen")};',
                  '}']
    # Complete every validation before replacing either reviewed output.
    args.output.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.output.with_name(args.output.name + '.tmp')
    temporary.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    temporary.replace(args.output)
    if args.header:
        args.header.parent.mkdir(parents=True, exist_ok=True)
        temporary = args.header.with_name(args.header.name + '.tmp')
        temporary.write_text('\n'.join(header) + '\n', encoding='utf-8')
        temporary.replace(args.header)
    print(f"{c['version']}: runtime profile {state}")


if __name__ == "__main__":
    main()
