#pragma once
// Generated by emit-runtime-config.py from the reviewed source-bound ABI facts.
#include "GuestModuleRuntime.h"
namespace StockABI {
inline constexpr char SourceCommit[] = "81526d4dc7cc70e4ae75abb35a789417456c6d43";
inline constexpr char Fingerprint[] = "166bb1c8a94fdb67d0765317568d1389b325abb2dd09f629e100f0c0a8f3973a";
inline constexpr GuestRuntime::Layout Registers{0, 512, 528, 1168, 672, 680, 1100, 676, 592};
inline constexpr unsigned RegisterPackSize = 1440;
inline constexpr unsigned ConfigSize = 1720;
inline constexpr unsigned AspectRatioOffset = 60;
inline constexpr unsigned GSWindowOffset = 128;
inline constexpr unsigned GSDeviceSize = 264;
inline constexpr unsigned WindowHandleOffset = 16;
inline constexpr unsigned SurfaceWidthOffset = 32;
inline constexpr unsigned SurfaceHeightOffset = 36;
inline constexpr unsigned EmuThreadSize = 96;
inline constexpr unsigned FullscreenOffset = 52;
}
