name: GitHub Actions Build

on:
  push:

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [Win64]
        buildtype: [Release]

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Configure build
      shell: cmd
      run: |
        ./premake5.bat
    - name: Build
      shell: cmd
      run: |
        msbuild -m build/PCSX2PluginInjector.sln /property:Configuration=${{matrix.buildtype}} /property:Platform=${{matrix.platform}}
    - name: Download Ultimate ASI Loader x64
      uses: robinraju/release-downloader@v1.11
      with:
        repository: "ThirteenAG/Ultimate-ASI-Loader"
        tag: "x64-latest"
        fileName: "version-x64.zip"
    - name: Unpack dependencies
      run: |
          7z x version-x64.zip -odata/ -y
          del version-x64.zip
          del data\version-x64.SHA512
    - name: Pack binaries
      run: |
        ./release.bat
    - name: Get release info
      id: release_info
      uses: cardinalby/git-get-release-action@master
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: latest
    - name: Upload Release
      uses: ncipollo/release-action@v1.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        name: ${{ steps.release_info.outputs.name }}
        body: ${{ steps.release_info.outputs.body }}
        tag: ${{ steps.release_info.outputs.tag_name }}
        artifacts: PCSX2PluginInjector.zip,PCSX2PluginInjectorDemo.zip
