name: GitHub Actions Build

on:
  push:

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [Win64]
        buildtype: [Release]

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Configure build
      shell: cmd
      run: |
        ./premake5.bat
    - name: Build
      shell: cmd
      run: |
        msbuild -m build/PCSX2PluginInjector.sln /property:Configuration=${{matrix.buildtype}} /property:Platform=${{matrix.platform}}
    - name: Pack binaries
      run: |
        ./release.bat
    - name: Get release info
      id: release_info
      uses: cardinalby/git-get-release-action@1.2.4
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: latest
    - name: Upload Release
      uses: ncipollo/release-action@v1.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        name: ${{ steps.release_info.outputs.name }}
        body: ${{ steps.release_info.outputs.body }}
        tag: ${{ steps.release_info.outputs.tag_name }}
        artifacts: PCSX2PluginInjector.zip,PCSX2PluginInjectorDemo.zip
